name: Build and Release BOSSFramework

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Zip source files
      run: zip -r BOSSFramework-Source.zip . -x '*.git*' 'bin/*' 'obj/*' '*.vs*'

    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          **/bin/Release/**/*.dll
          BOSSFramework-Source.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
