name: Publish Mod Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Build Release Assets
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload BOSSFramework.dll to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            path/to/BOSSFramework.dll
            path/to/BOSSFrameworkSource.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}